### ISSUE TITLE
$PATH is overridden

### ISSUE THREAD

**Issue by vencislaf** [thoughtbot/dotfiles#303]
Since 6a1bd18a1f20f8a384e5916a63e2b67d949eb02a $PATH is set in `.zshenv` instead of `.zshrc` and because of this it's overridden later by `/etc/zshrc`. The order in which zsh config files are loaded:

```sh
/etc/zshenv
~/.zshenv
/etc/zshrc
~/.zshrc
```

The problem wouldn't occur if `path_helper` is in `/etc/zshenv` file, but I think this is considered to be a bug in OS X. That's why the `thoughbot/laptop` script  moves the `/etc/zshenv` file to `/etc/zshrc` - https://github.com/thoughtbot/laptop/blob/49b8b3880b2bb2126ec7cefa015da94e206c386f/mac-components/zsh-fix#L3

My `$PATH` before 6a1bd18a1f20f8a384e5916a63e2b67d949eb02a

```sh
# good
.git/safe/../../bin:/Users/ventsi/.rbenv/shims:/Users/ventsi/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

and after

```sh
# bad
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:.git/safe/../../bin:/Users/ventsi/.rbenv/shims:/Users/ventsi/.bin
```

My temporary solution was to move `/etc/zshrc` back to `/etc/zshenv`. Any thoughts on what's the real solution?

**Comment by gylaz** [comment]
I believe this https://github.com/thoughtbot/laptop/pull/313 fixed this issue by not moving `/etc/zshenv` file to `/etc/zshrc`.
