### ISSUE TITLE
Adding /usr/local/bin & /usr/local/sbin in ~/.zshenv messes up $PATH

### ISSUE THREAD

**Issue by danielnolan** [thoughtbot/dotfiles#322]
On OSX Yosemite the adding `/usr/local/bin:/usr/local/sbin` `in ~/.zshenv` makes the path look like this:
 `.git/safe/../../bin:/Users/danielnolan/.rbenv/shims:/Users/danielnolan/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` 

Notice that /usr/local/bin is added twice and the order is a little messed up.

Yosemite adds the contents of `/etc/paths` to the `$PATH` via the path helper. 
The default `/etc/paths` file looks like:
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```
So since `/usr/local/bin` is already there it would seem appropriate to me to just add `/usr/local/sbin`
```
/usr/local/bin
/usr/bin
/bin
/usr/local/sbin
/usr/sbin
/sbin
```
Doing so loads the path in the proper order. 
`.git/safe/../../bin:/Users/danielnolan/.rbenv/shims:/Users/danielnolan/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin`

**Comment by gylaz** [comment]
I've just tried it, and adding `/usr/local/sbin` to `PATH` in `~/.zshenv` seems to work fine. 

@danielnolan have you moved `/etc/zshenv` to `/etc/zshrc`, or anything else that could be causing this issue?

**Comment by danielnolan** [comment]
@gylaz No I have not moved `/etc/zshenv` to `/etc/zshrc/`. And I am seeing this on two machines both running Yosemite.
So yours is in the proper order like `.git/safe/../../bin:/Users/danielnolan/.rbenv/shims:/Users/danielnolan/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin` ?

**Comment by gylaz** [comment]
I'm on a clean Yosemite install. When I add the following to my `~/.zshenv`:
```
export PATH="$HOME/.bin:$PATH"
export PATH="/usr/local/sbin:.git/safe/../../bin:$PATH"
export PATH=$GOPATH/bin:$PATH:/usr/local/mysql/bin
```
and `echo $PATH` produces:
```
/Users/greg/code/personal/go-lab/bin:/usr/local/sbin:
.git/safe/../../bin:/Users/greg/.rbenv/shims:/Users/greg/.bin:
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin
```
Do you have any `PATH` exports in other files? Any calls to `rbenv` or `brew` in your `~/.zsh*` files?

**Comment by danielnolan** [comment]
Mine looks the same as yours.. `usr/local/sbin` should not come before `usr/local/bin`... it should be 
`usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin`

**Comment by gylaz** [comment]
> `usr/local/sbin` should not come before `usr/local/bin`

I'm confused about this. Why should it not? I'm explicitly placing it before anything else in my path via:
```
export PATH="/usr/local/sbin:.git/safe/../../bin:$PATH"
```

**Comment by danielnolan** [comment]
I stand corrected, after some further research, it is ok to load `/usr/local/sbin` before `/usr/local/bin`. 
Closing this issue.
