### ISSUE TITLE
Reverse history search breaks cursor position

### ISSUE THREAD

**Issue by nickpad** [thoughtbot/dotfiles#339]
I've noticed that #335 looks like it's introduced a problem when using `Ctrl-r` to do a reverse history search in zsh. The cursor moves back into the prompt when in a git repository:

![reverse-search](https://cloud.githubusercontent.com/assets/588/6125702/1e56cebc-b16d-11e4-9723-cf6f65da89df.png)

The problem looks to have been introduced in the change to `zshrc` in [this commit](https://github.com/thoughtbot/dotfiles/commit/b0fe7c01ff24b40fe64736c1d5b2ac9d0f33477c).

I've spent a bit of time playing around with the prompt string but unfortunately haven't been able to work out where the problem lies yet.

**Comment by geoffharcourt** [comment]
I have the same issue. I had thought it was something wrong with my terminal setup.

**Comment by gylaz** [comment]
#340 has been merged. Can you try and see if latest on master fixes this?

**Comment by nickpad** [comment]
Can confirm that it's now fixed for me. Thanks!
