### ISSUE TITLE
Autocomplete git delete-branch as git-branch

### ISSUE THREAD

**Issue by croaky** [thoughtbot/dotfiles#355]
Anyone know how to do this? I took a few stabs but had no luck.

```
g delete-branch dc-<Tab>
```

**Comment by Keithbsmiley** [comment]
I've submitted  https://github.com/thoughtbot/dotfiles/pull/356 to do this. Please test it!

**Comment by hiattp** [comment]
+1

**Comment by ruiafonsopereira** [comment]
@keith, I'm not sure if that's the case here and in #356, but [this](http://www.zsh.org/mla/users/2010/msg00736.html) actually solved my problem.

**Comment by croaky** [comment]
My white whale.

**Comment by geoffharcourt** [comment]
@croaky, you and me. Still doesn't work with base dotfiles on El Cap.

**Comment by ruiafonsopereira** [comment]
@croaky @geoffharcourt 

Guys, consider switching from `git` plugin to `gitfast`. This actually solved my problem and my custom git commands are now autocompleted.

https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#gitfast

**Comment by geoffharcourt** [comment]
Hi @ruiafonsopereira,

I'm interested in seeing why `gitfast` might be able to handle the completion, and then bringing that capability into our dotfiles. Oh My Zsh is incredibly powerful, but we're unlikely to move our configuration over to require it.

**Comment by ruiafonsopereira** [comment]
@geoffharcourt, despite the fact that I couldn't see any reference to Oh My Zsh on these `dotfiles`, I assumed that you guys used it. My bad :smile: Nevertheless, I'm also interested to understand why `gitfast` solved the problem, but I couldn't find the time to do so yet. Please keep us updated if you learn something new.

**Comment by gylaz** [comment]
> my custom git commands are now autocompleted.

To be clear, the custom git commands are auto-completed currently as well. The issue is that for `delete-branch` custom command, the branches aren't autocompleted.

**Comment by geoffharcourt** [comment]
@gylaz: our white whale swims on.

**Comment by geoffharcourt** [comment]
Update: I can get tab-completion on `git delete-branch <tab>` with Keith's completion function and this addition to `zsh/configs/post/completion.zsh`:

```shell
    zstyle ':completion:*:*:git:*' delete-branch:'local branches'
```

But it breaks tab completion on our `g` function. I don't know enough about the nuances of `zstyle` yet to diagnose, but I'm continuing to investigate.

**Comment by geoffharcourt** [comment]
I have a solution proposed in #452. Please test it on your machine (make sure you run `rcup` before testing) and let us know if it works.
