### ISSUE TITLE
Organize by topic?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/dotfiles#366]
For example: https://github.com/holman/dotfiles

**Comment by derekprior** [comment]
I had this for a while in my personal dotfiles and found that it caused me to spend more time worry about where something should be filed or trying to remember where I might have filed something. Not everything tucks neatly into buckets.

It wasn't something that actively bothered me, but it's also not something I miss now that I don't have it.

**Comment by croaky** [comment]
Good to know. Any examples you remember of things that were hard to categorize?

**Comment by jferris** [comment]
RCM supports this. I know @pbrisbin does this with his dotfiles: https://github.com/pbrisbin/dotfiles

**Comment by geoffharcourt** [comment]
This gives me heartburn. I am already somewhat regretting breaking my personal `.vimrc.local` into sub-files by topic, as I time guessing or searching for where I set a given option.

**Comment by geoffharcourt** [comment]
I'm happy to reopen this if there's momentum behind it, but we haven't discussed it in several months.
