### ISSUE TITLE
.zchrc

### ISSUE THREAD

**Issue by ahmgeek** [thoughtbot/dotfiles#370]
I was have zch and oh-my-zsh on top of it, after installing dotfiles I've tried to re theme it and using the usual oh-my-zsh aliases but couldn't do that!
where'es the actual .config file ? 
every change on the usual .zshrc never took effect.
and no post and before directories on /.zsh/

**Comment by gylaz** [comment]
Can you provide a little more information about what isn't working?

**Comment by JoelQ** [comment]
You've typo'd `zch` and `zchrc` a few times in this issue. Could the issue be caused by a typo'd config file name?

**Comment by ahmgeek** [comment]
ok, from where I can change the theme of oh-my-zsh ?

**Comment by gylaz** [comment]
That would be a question better posed to `oh-my-zsh` maintainers. I have no experience running these `dotfiles` with `oh-my-zsh`

**Comment by Jaicob** [comment]
Incase anyone else finds themselves here with the same problem, you need these lines in your `zshrc` or `.zshrc.local`

```
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
```

**Comment by chandresh** [comment]
I run into same problem and doing the following fixed it for me:

`cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc.local`
