### ISSUE TITLE
ctags.vim

### ISSUE THREAD

**Issue by danielnolan** [thoughtbot/dotfiles#374]
Is the ctags.vim plugin even used? If I run the CTAGS command I just get a bunch of errors. There seems to be a updated version that allows displaying the ctagged function name in the status bar rather than the title bar. https://github.com/vim-scripts/ctags.vim--Johnson

**Comment by gylaz** [comment]
How do you run the ctags command? `:!ctags -R .<CR>` works for me, but I'm not actually sure what the plugin does.

**Comment by danielnolan** [comment]
`:!ctags -R ` is just calling ctags in the shell. That plugin is not needed to generate ctags, it's supposed to show the function name that you have the cursor over in the title bar based on the vim scripts description. I've never used it since switching to TB dotfiles, and it doesn't seem to work. The command to run it according to their docs is `:CTAGS`. If I run that it blows up.

**Comment by geoffharcourt** [comment]
The plugin doesn't have documentation, but it seems like the purpose of the plugin is to build ctags every time you enter or save a buffer, and to display the name of the current method in the buffer's title. 

When I run the plugin's `:CTAGS` command, my vim session is more or less broken until I quit and restart. Given that we're building the tags using a git hook and the plugin is currently abandoned and doesn't work in the thoughtbot configuration out of the box, I think it's a good candidate for removal.

**Comment by gylaz** [comment]
> the purpose of the plugin is to build ctags every time you enter or save a buffer

Definitely doesn't work for me. I've opend #375 to remove it.

**Comment by croaky** [comment]
Fixed in https://github.com/thoughtbot/dotfiles/commit/7aba66a9d6f813644c2a87f4b59b1f739eacd9c6
