### ISSUE TITLE
Using terminal.app, new tab doesn't open in the same directory

### ISSUE THREAD

**Issue by iamarmanjon** [thoughtbot/dotfiles#378]
Hi! I just reformatted my mac, and when I was still using bash shell, my current directory is saved when I create a new tab e.g. Downloads folder, still in downloads folder when I open a new tab.

It was lost when I install dotfiles. What settings should I edit? Thanks

Please closed this if this issue was resolved already, can't find it in the other issues when I searched.

**Comment by geoffharcourt** [comment]
@iamarmanjon, this is a setting in Terminal.app.

In Preferences, look at the General tab. There's an option at the bottom that controls the folder to be used for new tabs and one for new windows as well.

**Comment by iamarmanjon** [comment]
Yes @geoffharcourt. It's already like that. When I use the bash shell it's opening new tab in the current directory. But when I use the iTerm, it behaves like normal. I just want to avoid duplicate apps, maybe there is a settings I need to tweak in the script?

**Comment by gylaz** [comment]
There is nothing in the dotfiles that changes this behavior. Are you using iTerm2 or Terminal?

**Comment by BlakeWilliams** [comment]
I ran into this a long time ago when switching from bash to zsh. I think it's an issue with zsh/terminal, not the dotfiles.

I *think* this is what I used to fix it. https://github.com/BlakeWilliams/dotfiles/blob/f8a02ce6fc80c74d043768e7418974b3d9d16dbe/.zshrc#L48-L57

**Comment by iamarmanjon** [comment]
@BlakeWilliams Sir you are the man! Thanks for this. It fixed it.
