### ISSUE TITLE
Alternate between spec and lib files in Vim?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/dotfiles#381]
When I'm working in a gem, I don't have the nice `:A` I'm used to from Rails.vim, alternating between spec/models/user_spec.rb to app/models/user.rb, for example.

In a gem, we pretty regularly have `spec` and `lib` directories. Wondering if anyone has a favorite setup for this scenario? I see https://github.com/clembradley/alt-ruby as maybe having potential.

**Comment by calleerlandsson** [comment]
I think `:A` For non-Rails projects is in [vim-rake](https://github.com/tpope/vim-rake/).

**Comment by geoffharcourt** [comment]
@croaky, @calleerlandsson, [vim-rake](https://github.com/tpope/vim-rake) adds this functionality, but it only did it automatically if I also installed [vim-projectionist](https://github.com/tpope/vim-projectionist). This is implied from the vim-rake instructions, but vim-rake will install without error if you forget vim-projectionist.

**Comment by croaky** [comment]
I believe @calebthompson is a vim-projectionist user, too. Looks useful, will have to give it a shot.

**Comment by geoffharcourt** [comment]
The side benefit of projectionist vs. alt-ruby is that while it adds the default `:A` behavior (with vim-rake), you can easily add some project- or global-level shortcuts similar to vim-rails' projections.

It appears that Tim Pope is [moving vim-rails to eventually piggyback on top of vim-projectionist](https://github.com/tpope/vim-rails/commit/609227534f11a7cf7b3ba1cf51c79b72e5c9ba1b), which would give it some further points as a good default solution.

**Comment by croaky** [comment]
Nice, looks cool
