### ISSUE TITLE
Terminal Profile

### ISSUE THREAD

**Issue by blainesch** [thoughtbot/dotfiles#407]
I setup a few computers with my fork of these dotfiles and one thing I always end up doing is changing the profile to be a bit nicer looking. I decided to see what the effort was in automating this with a custom profile ([Solarized Dark](https://github.com/tomislav/osx-terminal.app-colors-solarized) in this case), although I could remove a few lines to make this work for a default profile. I accomplished this with a bash script and a apple script.

Is this something that others might want as part of this repo?

The example lives here:
https://github.com/blainesch/terminal-theme

**Comment by geoffharcourt** [comment]
While I am also a frequent Solarized user, I think terminal settings are something that are really personal. I think a better way to make this easy to include would be to "homebrew-ify" that repository and then to add it to a `laptop.local` file for use with Laptop's personal setup feature.

**Comment by blainesch** [comment]
I ended up making it a rubygem [over here](https://github.com/blainesch/terminal-profile-manager). This can still be automated in the laptop config, which I've not used until now. Here is an example of the [laptop.local](https://github.com/blainesch/dotfiles/blob/master/laptop.local#L3-L6) I added to install this correctly.

**Comment by blainesch** [comment]
A bit of a chicken/egg problem here though.

Since laptop installs `rcm` and you need `rcm` to have a `laptop.local` file via `dotfiles`, which is necessary for installing your custom laptop config.

**Comment by geoffharcourt** [comment]
That's true, but I believe Laptop is idempotent, so you can install laptop, install your personal dotfiles, and then re-run Laptop to get the changes in place.
