### ISSUE TITLE
Update `$PATH` for el capitan?

### ISSUE THREAD

**Issue by jessieay** [thoughtbot/dotfiles#429]
Upgraded to El Capitan on Friday and suddenly rbenv stopped working. 

```bash
ruby -v
> ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
rbenv local
> 2.2.3
echo $PATH
>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.rbenv/shims:.git/safe/../../bin:/Users/jessicayoung/.bin:/usr/local/sbin
```

Updated $PATH in `.zshenv.local` to:

`export PATH="/Users/jessicayoung/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:$PATH"` and:

and then: 

```bash
echo $PATH
> /Users/jessicayoung/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:~/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.rbenv/shims:.git/safe/../../bin:/Users/jessicayoung/.bin:/usr/local/sbin
ruby -v
> ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
```

Not sure I understand why exactly this is the case, but I got to this solution via https://github.com/sstephenson/rbenv/issues/791

Perhaps something needs to change in the $PATH for El Capitan?

**Comment by derekprior** [comment]
Hi @jessieay! We've been talking about this some.

See: https://github.com/thoughtbot/dotfiles#note-for-os-x-el-capitan-users

... and related fallout here: https://github.com/thoughtbot/dotfiles/pull/426

**Comment by jessieay** [comment]
AH ok thanks, was looking for a github issue about el capitan but didn't see one...thanks for the links! Does this mean that my solution is not the desired solution?

**Comment by jferris** [comment]
We're still trying to figure out which solution is best, so I don't think we can say there is a single desired solution yet.

However, it's not clear to me how your solution works! My understanding of the El Capitan change is:

* `path_helper` used to change the path in `/etc/zshenv`
* In El Capitan, it started changing the path in `/etc/zprofile` instead
* `/etc/zprofile` is evaluated after `~/.zshenv`, so it would override the changes you made to your path

It seems like this would also apply to `~/.zshenv.local`, though, so I don't get how setting it there fixed your problem.

These paths are making me thirsty!

![](https://41.media.tumblr.com/a7e0d740bb9aca355d25e1d42f217c43/tumblr_moinrpZbA61qjuq0oo1_500.png)

**Comment by jessieay** [comment]
You know what - I actually did a `source ~/.zshenv.local` rather than running `rcup` - I see know that running `rcup` messes up my `$PATH` again. So it seems that my "solution" is more of a bandaid. :baby_chick:

**Comment by jferris** [comment]
Ah, that makes sense. If you re-source `~/.zshenv.local` without also re-running `path_helper`, it would append the paths as expected.

I'm going to close this, as we already have issues tracking the `PATH` problem, but please do chime in if you have thoughts or ideas.
