### ISSUE TITLE
Path is duplicated inside a tmux session

### ISSUE THREAD

**Issue by maletor** [thoughtbot/dotfiles#443]
```
~ % path
.git/safe/../../bin
/Users/maletor/.rbenv/shims
/Users/maletor/.bin
/usr/local/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
.git/safe/../../bin
/Users/maletor/.rbenv/shims
/Users/maletor/.bin
/usr/local/sbin
```

**Comment by geoffharcourt** [comment]
We have an open discussion on #440 that should resolve this problem. For the time being, as long as the first occurrence of each folder comes in the proper order, I am not aware of serious consequences to path entries being duplicated.

**Comment by maletor** [comment]
:tada: 

Thanks!

**Comment by geoffharcourt** [comment]
:+1:
