### ISSUE TITLE
can I install this on my Elementary OS(Linux)? 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [thoughtbot/dotfiles#466]

**Comment by jferris** [comment]
Yes! Several of us (myself included) use dotfiles on various distros of Linux.

**Comment by AbhimanyuAryan** [comment]
@jferris but the commands in installation process uses brew. Homebrew is not a linux package manager?

**Comment by jferris** [comment]
Hmm, yeah, the rcm install example uses `brew`. You can install rcm however you'd like, though. It has packages for several distros, including Debian, Arch, and Ubuntu. Check out the install instructions: https://github.com/thoughtbot/rcm#installation
