### ISSUE TITLE
:NERDTree doesn't work. It was working earlier

### ISSUE THREAD

**Issue by AbhimanyuAryan** [thoughtbot/dotfiles#468]
$ cat .vimrc.local

" Color scheme
colorscheme obsidian
highlight NonText guibg=#060606
highlight Folded  guibg=#0A0A0A guifg=#9090D0

autocmd VimEnter * NERDTree

error says 
E492: Not an editor command : NERDTree

**Comment by AbhimanyuAryan** [comment]
Ok it worked by mistake I removed .dotfile dir from home directory. I need to move it some else where

**Comment by teoljungberg** [comment]
Glad it sorted itself out
