### ISSUE TITLE
vim complains about chars in .vimrc

### ISSUE THREAD

**Issue by qrkourier** [thoughtbot/dotfiles#492]
`~ % vim .vimrc
Error detected while processing /home/qrk/.vimrc:
line   60:
E474: Invalid argument: listchars=tab:����,trail:��,nbsp:��
`

The culpable characters are in order of appearance:

> Alt-B   \302   C2   U+00C2   &Acirc;    Â  capital A, circumflex accent
> Alt-;   \273   BB   U+00BB   &raquo;    »  open (or close) chevron-style quotes
> \267

**Comment by geoffharcourt** [comment]
Hi @qrkourier, can you let me know what version of Vim and OS you're using? I'm unable to reproduce that problem on my machine.

**Comment by mike-burns** [comment]
@qrkourier what are your language settings? What is the output of `env | egrep '(LC|LANG)'` ?

**Comment by geoffharcourt** [comment]
Hi @qrkourier if you can report back in with some more information, we'll reopen this issue and take a look at what might be wrong.
