### ISSUE TITLE
Command line option to overwrite

### ISSUE THREAD

**Issue by sandeep048** [thoughtbot/dotfiles#494]
Is there a command line option for rcup to automatically overwrite any existing file? This is slightly ugly.

```
yes y | rcup -v
overwrite /home/sandeep/.byobu/keybindings.tmux? [ynaq] removed '/home/sandeep/.byobu/keybindings.tmux'
'/home/sandeep/.dotfiles/byobu/keybindings.tmux' -> '/home/sandeep/.byobu/keybindings.tmux'
```

**Comment by geoffharcourt** [comment]
@sandeep048 `rcup` is part of rcm, I think this issue should be filed here: https://github.com/thoughtbot/rcm/issues
