### ISSUE TITLE
Is there a way to remove?

### ISSUE THREAD

**Issue by jdgonzales09** [thoughtbot/dotfiles#495]
There are some issues with the way git is operating and I want to remove all variables that could contribute. On top of this, Vim started to act weird. Is there a way to remove all the dotfiles configuration?

**Comment by blainesch** [comment]
`rcdn` -> https://thoughtbot.github.io/rcm/rcdn.1.html

**Comment by geoffharcourt** [comment]
@jdgonzales09, `rcdn` should do it. If you isolate a particular problem we can address, please submit a PR.
