### ISSUE TITLE
zsh colors unreadable

### ISSUE THREAD

**Issue by lpender** [thoughtbot/dotfiles#496]
Hi!

I noticed that the default zsh colors are very low contrast, and there's no documentation on how to change or update the zsh color scheme. Would be lovely to see an implementation...

![image](https://cloud.githubusercontent.com/assets/1406554/16892403/83636f06-4adf-11e6-801e-4265c36f8250.png)

Thanks!

**Comment by geoffharcourt** [comment]
@lpender I think this is likely better handled in your terminal's color scheme configuration. Other than enabling color output, dotfiles currently doesn't make any decisions about what color scheme you use in zsh.
