### ISSUE TITLE
zsh profile, plugins not loading after install 

### ISSUE THREAD

**Issue by t0nylombardi** [thoughtbot/dotfiles#502]
dotfiles .zshrc overwrites the generic oh-my z-shell .zshrc settings which comes with themes and plugins for aliases.  A lot of functionality gets lost in the setup.  

Would it be possible to incorporate the bulk of zsh into dotfiles? I've added a folder called plugins and  used To add some of the plugins that are in the .oh-my-zsh dir: 
```
for function in $HOME/dotfiles/plugins/*; do
  source $function
done
```

**Comment by geoffharcourt** [comment]
Hi @t0nylombardi, oh-my-zsh is not something we're going to explicitly support in dotfiles, but I suspect you could hack together your own `zshrc` that does the same loading the base dotfiles uses (that's unlikely to change much) and then to append that to your oh-my-zsh-capable `zshrc`. With https://github.com/thoughtbot/rcm, if your personal dotfiles folder has higher precedence than the base dotfiles, your customized `zshrc` will "win" and overwrite the base `zshrc`.

**Comment by unmultimedio** [comment]
I'm on the same position. Just started to play around with dotfiles, and really learning, could you explain how do I include om-hy-zsh functionalities if I already downloaded this dotfiles and want to keep both? Mainly for the oh-my-zsh plugins.

**Comment by geoffharcourt** [comment]
dotfiles zsh philosophy is considerably lighter-weight than oh-my-zsh's is, but I think if you wanted to integrate both at the same time the easiest approach would be to take whatever oh-my-zsh wants in ~/.zshrc and to put those files in zsh/configs/post/oh-my-zsh.zsh so that they are loaded at the end of the zsh load process and take precedence.

**Comment by t0nylombardi** [comment]
@unmultimedio  I added a folder called plugins && and in my alias file I loaded separate files in :

```shell
# load custom aliases
for function in $HOME/dotfiles/plugins/*; do
  source $function
done
```

@geoffharcourt  has a better idea though.

**Comment by geoffharcourt** [comment]
@t0nylombardi nice idea! Either way it's easy to flip oh-my-zsh on and off which I think would be nice to see what you're getting from the base shell/dotfiles settings vs. the framework.

**Comment by unmultimedio** [comment]
I decided to go with @geoffharcourt suggestion, although had a bit of trouble since the path was missing a dot haha, I tried placing it into `dotfiles/zsh/configs/post` and that didn't work... but actual path _(after this dotfiles are installed)_ is `.zsrc/configs/post`.

Now plugins are working all ok. Thanks!

**Comment by pjatx** [comment]
This is my first attempt at using dotfiles and I can't for the life of me get oh-my-zsh to load custom configs. Have tried putting the `oh-my-zsh.zsh` file in the following directories without success. 

Should be noted that I installed oh-my-zsh after dotfiles. 

```
.zsh/zsh/configs/post/
dotfiles/zsh/configs/post/
dotfiles-local/zsh/configs/post
~/.zsrc/configs/post
```

What am I missing here?

**Comment by geoffharcourt** [comment]
@pjatx I suspect you haven't run `rcup` to resync your dotfiles -> symlinks under your home directory.

Also possible problem: is `~/.zsrc` a typo?
Also possible problem: the first directory item looks like it's got an extra level of `.zsh`.

**Comment by pjatx** [comment]
Thanks @geoffharcourt after banging my head on it a while longer I was able to figure it out. 

Involved running rcup and implementing antigen as well which makes things a bit easier. 

Thanks for the reply!
