### ISSUE TITLE
vim-plug has to be installed first

### ISSUE THREAD

**Issue by rrocchi** [thoughtbot/dotfiles#504]
Just tried to install this on a new ubuntu server with an empty home directory. Following the readme I've got spammed with the message:
You are using Vundle's `Plugin` command to declare plugins. Dotfiles now uses vim-plug for plugin management. Please rename uses of `Plugin` to `Plug`. Plugin was 'vim-scripts/tComment'.
E169: Command too recursive

To make it work I had to install vim-plug first and then re-run rcup:

`curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`

It would be nice to ask rcup to install vim-plug if it's not already installed or at least add this step to the readme.

**Comment by geoffharcourt** [comment]
@rrochi there's actually a hook in `hooks/post-up` that does exactly what you suggest. Can you walk me through the steps you took that led to the problem?

**Comment by rrocchi** [comment]
Hi Geoff,

This was on a brand new ubuntu 16.04 server and installing the dotfiles was literally the first thing that I did. Best I can do is to show you my bash history:

```
sudo apt install vim  
sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm  
sudo apt-get install software-properties-common  
sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm  
sudo apt-get update  
sudo apt-get install rcm  
cd  
git clone git://github.com/thoughtbot/dotfiles.git ~/dotfiles  
sudo apt install git  
git clone git://github.com/thoughtbot/dotfiles.git ~/dotfiles  
git clone https://bitbucket.org/jebrook/dotfiles-local.git  
chsh -s $(which zsh)  
sudo apt install zsh  
chsh -s $(which zsh)
```

For some reason the zsh history didn't start until I logged out, but the next line after the ones above was
`env RCRC=$HOME/dotfiles/rcrc rcup`
 
Once I've got spammed with errors I thought that maybe my own dotfiles were causing the problem since the message was pointing to the last plugin in my vimrc.bundles.local so I deleted the dotfiles-local folder along with all the symlinks. But when I re-run rcup, the error message was now pointing to vim-scripts/tComment which is the last line or vimrc.bundles

It wasn't happy until I manually installed vim-plug as indicated in my previous message.

Hope that helps.

**Comment by geoffharcourt** [comment]
How mysterious! Is it possible you didn't have curl installed when you first ran `rcup`? I'm just reaching for a possible cause.

**Comment by rrocchi** [comment]
Yes! Clever you! I didn't have curl installed at the time. I had to install it in order to install vim-plug. Now I feel silly tho...

**Comment by geoffharcourt** [comment]
No worries. Glad we cleared it up!
