### ISSUE TITLE
The silver searcher and gitignore dependencies

### ISSUE THREAD

**Issue by anhari** [thoughtbot/dotfiles#507]
I recently started having issues with the silver searcher, and wanted to know what everyone thinks of adding the following to the `gitignore`?

- `vendor/bundle/`
- `node_modules/`
- `bower_components/`
- `tmp/` (for some reason `tmp/**/*` is not working – I'm not sure if the silver searcher stopped supporting globbing or what)

Adding these to my `gitignore.local` dotfile does not seem to work (Ag will still fly through them).

**Comment by mikegee** [comment]
There is a [`.agignore`](https://github.com/thoughtbot/dotfiles/blob/master/agignore) file that should accomplish what you want. I'm not sure why it isn't working for you.

**Comment by anhari** [comment]
Ah I forgot about `.agignore`.  Okay, I think this is related to  [Issue #100 on the silver searcher](https://github.com/ggreer/the_silver_searcher/issues/100) so I'm going to close this.

**Comment by anhari** [comment]
Just now realizing that git isn't respecting my `gitignore.local` file either.
