### ISSUE TITLE
README: Make your own customizations

### ISSUE THREAD

**Issue by rootulp** [thoughtbot/dotfiles#511]
I think the [Make your own customizations](https://github.com/thoughtbot/dotfiles#make-your-own-customizations) section could be made clearer by instructing users to use `~/dotfiles-local`. Currently, the explanation for `rcup` includes the following bullet point: 

> Give precedence to personal overrides which by default are placed in `~/dotfiles-local`

but the make your own customizations does not instruct users to place their local customizations in `~/dotfiles-local`. Instead it reads:

> Put your customizations in dotfiles appended with `.local`:
> - ~/.aliases.local
> - ~/.git_template.local/*
> - ...

I think this section should read:

> Create a directory for your personal customizations: `mkdir ~/dotfiles-local`
> Put your customizations in `~/dotfiles-local` appended with `.local`: 
> - ~/dotfiles-local/aliases.local
> - ~/dotfiles-local/git_template.local/*
> - ...

This makes it easier for users to version control their personal customizations in `dotfiles-local`
I'd be happy to make the changes if this seems sensible.

**Comment by anhari** [comment]
I'd include the rcup command to sync those as well: `rcup -d ~/dotfiles-local -v`

**Comment by geoffharcourt** [comment]
@anhari I think the existing [`.rcrc`](https://github.com/thoughtbot/dotfiles/blob/master/rcrc) handles that for you.

**Comment by geoffharcourt** [comment]
In #513 the documentation was updated. Closing!

**Comment by anhari** [comment]
So I recently had the idea of spinning up a `dotfiles-local` template repo that could be forked by new users as well.  I've actually switched an entire team to use this set up and the only painstaking process is manually spinning up a repo and creating local files for customizations.  What do you think of thoughtbot hosting a forkable `dotfiles-local` repo for new users?
