### ISSUE TITLE
Mysterious alias: `git up`

### ISSUE THREAD

**Issue by jessieay** [thoughtbot/dotfiles#515]
Hola --

I run `git up` about a zillion times a day. It fetches updates from master and rebases my current branch on top of those. 

I always thought this alias came from the thoughtbot dotfiles...but now I cannot find it in here anywhere. This morning I updated my local dotfiles to contain the latest master from this repo, but I still have `git up` available and I do not see it when running `git config --global --list`

Does anyone know where this alias might be coming from? I am stumped!

**Comment by gylaz** [comment]
A lot of git aliases have been moved to binaries: https://github.com/thoughtbot/dotfiles/tree/master/bin

**Comment by geoffharcourt** [comment]
Hi @jessieay!

It's not an alias, it's a git command, `git-up`.

**Comment by jessieay** [comment]
ooooh! so it is. Thank you for solving this mystery. 

Now a related question: would there be an easy way to make this command know what my base branch is? Increasingly, I am working off of a base branch of `develop` which auto-deploys to staging when it passes CI. `master` auto-deploys to prod so we merge `develop` into `master` regularly. 

This is not true for all of my projects so I wouldn't want to update the command to always assume a base branch of `develop`....but it would be nice if it were smart enough to rebase off of `origin/develop` rather than `master` on this particular repos...

**Comment by gylaz** [comment]
What I've done in the past is copy `git-up` into my project's `bin/` (if you're sell is setup to prioritize that) and updated the script to point to `origin/develop`.

**Comment by croaky** [comment]
Hiiii @jessieay

**Comment by jessieay** [comment]
👋 👋 👋 👋 👋 👋
