### ISSUE TITLE
Running rcup results in strange terminal state requiring reset

### ISSUE THREAD

**Issue by entcheva** [thoughtbot/dotfiles#516]
Running `env RCRC=$HOME/dotfiles/rcrc rcup` after successful `brew install rcm` results in Vim error and leaves terminal in a strange state that requires a reset.

Error:
```
Vim: Warning: Input is not from a terminal
Vim: Caught deadly signal ABRT
Vim: Finished.
```

Formatting in terminal no longer has line breaks and requires reset to appear as intended.

**Comment by geoffharcourt** [comment]
I get this same problem! Finally someone recreated it.

Can you let me know what terminal and Vim version you're using?

**Comment by devinrm** [comment]
I get this as well.
![screen shot 2017-04-03 at 9 47 13 am](https://cloud.githubusercontent.com/assets/13222919/24612341/09ebf728-1853-11e7-91c0-5e9f230808f8.png)


iTerm2, Build 3.1.beta.2
tmux 2.3
VIM 8.0.535
NeoVim v0.2.0-1162-gbc6d868d

**Comment by geoffharcourt** [comment]
In https://github.com/thoughtbot/dotfiles/pull/510 I attempted to resolve this problem, but it broke `rcup` for several users who hadn't been experiencing my issue, so I reverted it. Now that we've got several people who experience the problem, maybe we can nail down what the issue is. I suspect that `tmux` is the issue since this doesn't appear to be a vim vs. Neovim issue (the post-up hook executes vim, not Neovim in any event).

**Comment by mikegee** [comment]
Random data point: I've never seen this issue and I don't use tmux.

**Comment by devinrm** [comment]
@geoffharcourt I just tried running rcup outside of tmux and I still have the same issue. However #510 fixes it for me (in and out of tmux), so I'm going to use that for now.

**Comment by rjdellecese** [comment]
I've been getting this for a while now too (`Vim: Warning: Input is not from a terminal`). If it's helpful:

- iTerm 3.0.15
- tmux 2.3
- Vim 8.0.0531

I also use Neovim (0.1.7), though as discussed it seems like that shouldn't matter.

**Comment by geoffharcourt** [comment]
@devinrm if you start a terminal with no tmux ever having been run in the terminal do you have the issue?

**Comment by devinrm** [comment]
@geoffharcourt Yep. I just downloaded iTerm 3.0.15 ran it from disk without starting tmux and got the same message (Vim: Warning: Input is not from a terminal)

**Comment by devinrm** [comment]
I don't know if this is helpful but if you change it so that the post up hook executes from neovim, it works fine: `nvim -u "$HOME"/.vimrc.bundles +PlugInstall +PlugClean! +qa`

**Comment by entcheva** [comment]
Hi @geoffharcourt, I’m using:
- vim 7.3
- zsh 5.0.2

**Comment by pmkhoa** [comment]
Same issue. This causes dotfiles not create symlink properly.
- vim: 8.0
- iTerm: 3.0.14
- zsh: 5.0.8

**Comment by mike-burns** [comment]
How about calling `reset` after the vim command runs?

**Comment by entcheva** [comment]
Yup, after `reset` formatting appears as expected.

**Comment by geoffharcourt** [comment]
@mike-burns you are a hero.

**Comment by geoffharcourt** [comment]
With a `reset` inserted after the `vim` line in `post-up`, I get this output before getting a shell prompt again:

```
Erase set to delete.
Kill set to control-U (^U).
Interrupt set to control-C (^C).
```

I assume this is harmless (everything appears to work fine), but wasn't sure if we should worry about it. Can't find anything notable in web searches about it.

cc: @mike-burns

**Comment by mike-burns** [comment]
reset(1) says:

```
       -Q   Do not display any values for the erase, interrupt and  line  kill
            characters.  Normally tset displays the values for control charac‐
            ters which differ from the system's default values.
```

So, try passing `-Q`.

**Comment by geoffharcourt** [comment]
Thank you @entcheva @devinrm @mike-burns @pmkhoa @mikegee @rjdellecese for your help investigating and fixing!
