### ISSUE TITLE
Where are the key mapping docs for Vim

### ISSUE THREAD

**Issue by dan-klasson** [thoughtbot/dotfiles#525]
Where can I find the docs for the key mappings? The README only mentions what what plugins installed and not how to use them.

**Comment by geoffharcourt** [comment]
Hi @dan-klasson there are a number of ways to get all of the available mappings in your Vim config. `:map` will list every mapping you have. I like to use the `:Maps` command from https://github.com/junegunn/fzf.vim, which allows for some fuzzy searching.
