### ISSUE TITLE
zshenv.local does not get sourced

### ISSUE THREAD

**Issue by jordancalder** [thoughtbot/dotfiles#528]
I noticed that when I create the `~/dotfiles-local/zshenv.local` file, it doesn't get sourced. There is a call to `[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local`, however the symlink `.zshenv.local -> /Users/username/dotfiles-local/zshenv.local` does not exist. Did I do something wrong in the setup?

**Comment by gohanlon** [comment]
Sounds like you are *almost* there. I can't be sure so please forgive me if I'm wrong, but have you [installed and setup "rcm"](https://github.com/thoughtbot/dotfiles/blob/master/README.md#install)?

In case you're not familiar with the [thoughtbot/rcm](https://github.com/thoughtbot/rcm) project, the thoughtbot/dotfiles are [configured](https://github.com/thoughtbot/dotfiles/blob/master/rcrc#L2) to use the `rcup` command from "rcm" to create symlinks from your home directory to the files in both your `~/dotfiles` and `~/dotfiles-local` directories, e.g. to symlink:

```
~/.zshenv -> ~/dotfiles/zshenv
```

And:

```
~/.zshenv.local -> ~/dotfiles-local/zshenv.local
```

The other idea that comes to mind is perhaps you purposefully created your own "rcm" configuration (e.g. at `~/.rcrc`), but didn't include the second dotfiles directory of `~/dotfiles-local`? 

Does that help?

**Comment by geoffharcourt** [comment]
@gohanlon thank you for the help!

@jordancalder one thing to check for is what directories are in your `.rcrc` file. If your dotfiles aren't in `$HOME/dotfiles-local` and you didn't declare the directory in your rcm settings, they might not be sourced.

**Comment by jordancalder** [comment]
@gohanlon @geoffharcourt Weird. I did have rcm installed and setup and most of the symlinks were present. I re-ran `rcup` and the symlink was created. Are the symlinks only created if the `.local` file exists?

In any case, thanks for the help.
