### ISSUE TITLE
.zsh dotfile conflicting with oh-my-zsh theme?

### ISSUE THREAD

**Issue by discotroll65** [thoughtbot/dotfiles#531]
Hey, I'm appearing to have trouble setting my oh-my-zsh theme after running rcup with the thoughtbot dotfiles. I tried putting in the contents of the .zshrc into my `dotfiles-local/zsh/config/pre` , but it doesn't appear to be working... any help?

**Comment by discotroll65** [comment]
Closing this issue... I think it was just a silly mistake on my part.

**Comment by coisnepe** [comment]
@discotroll65 Would you mind sharing what was your mistake? I'm running into a similar issue.

**Comment by discotroll65** [comment]
@coisnepe  I forget what it was exactly, but if I had to guess I just needed to resource my terminal's profile... this can be accomplished by the classic "turn it off and on again" approach of closing all the terminal instances and starting it again.

**Comment by geoffharcourt** [comment]
I should also state that we don't support oh-my-zsh, so if you're using that you may have other conflicts.

**Comment by paulrberg** [comment]
@geoffharcourt is that still the case today? Do you still not support oh-my-zsh?
