### ISSUE TITLE
dotfiles uninstallation 

### ISSUE THREAD

**Issue by ayooby** [thoughtbot/dotfiles#537]
Hey guys,
I wanna to know is there any chance to remove `thoughtbot/dotfiles` to remove from my mac.
I didn't like it but I don't know how to remove it.

**Comment by geoffharcourt** [comment]
@ayooby you can use `rcdn` from the [rcm utility](https://github.com/thoughtbot/rcm) to remove the symlinks and then delete the directory on your file system where you downloaded or cloned the repository.
