### ISSUE TITLE
Tags / releases?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/dotfiles#540]
I'd like to mention Dotfiles releases in our weekly newsletter (also includes weekly blog posts and podcast episodes): https://robots.thoughtbot.com/

I can mention recent work by SHA but it feels kind of funny. Would it be weird to have releases / tags? What would be a good version number if we started tagging / releasing?

![screen shot 2017-08-10 at 5 17 10 pm](https://user-images.githubusercontent.com/198/29197483-91618bb6-7df0-11e7-9bb2-420f9b60112a.png)

**Comment by jferris** [comment]
Maybe use the date as the version?

**Comment by gabebw** [comment]
[youtube-dl uses the date](https://github.com/rg3/youtube-dl/tags) as the version and I like it as a consumer.

**Comment by geoffharcourt** [comment]
I think using the date but still linking to the SHA will result in the minimum amount of upkeep needed and a nice amount of information communicated.

**Comment by geoffharcourt** [comment]
I went with the date for [today's release](https://github.com/thoughtbot/dotfiles/releases/tag/20170915). Let's see how this goes! Thanks for setting this up, @croaky.
