### ISSUE TITLE
error: Error detected while processing CursorHold Auto commands for "*"

### ISSUE THREAD

**Issue by kevindashgit** [thoughtbot/dotfiles#542]
I followed your install procedure.

I opened up vim - and after typing any character (a few milliseconds later) I would get this error:
`Error detected while processing CursorHold Auto commands for "*"`

I commented out these line from your `.vimrc`: 
```
  52 "    autocmd CursorHold * call ale#Lint()
  53 "    autocmd CursorHoldI * call ale#Lint()
  54 "    autocmd InsertEnter * call ale#Lint()
```
Now I don't see the error but I also am probably missing out on some intended functionality.

I have no idea what this does or why it doesn't work and would love to see this working for me out of box.

**Comment by christoomey** [comment]
Hi @kevindashgit, we recently added [ALE](https://github.com/w0rp/ale) in place of Syntastic, with the associated auto commands that seem to be causing you an issue. Can you confirm the following:

1. Have you run `:PlugInstall` lately / since pulling in recent dotfiles changes?
2. Assuming `:PlugInstall` doesn't sort this out, can you share the output of running `:echo v:version` and `echo exists("g:has_async")`?

**Comment by kevindashgit** [comment]
Running `:PlugInstall` did the trick!

I saw one of the new things that got updated was this:
`ale: Resolving deltas: 100% (868/868), done.`

Thanks @christoomey!

Also, I wonder if it makes sense to add this little gem in the `Readme`?  Would have made this experience a bit smoother for folks like me that are rather new to this stuff.

**Comment by christoomey** [comment]
Reading a bit closer, I'm remembering that this functionality is actually built into the `rcm` configuration. Per the README:

> You should run `rcup` after pulling a new version of the repository to symlink any new files in the repository.

This line undersells it a bit, as running `rcup` will do everything in the [post-up hook file](https://github.com/thoughtbot/dotfiles/blob/master/hooks/post-up) which includes a command to install any new Vim plugins](https://github.com/thoughtbot/dotfiles/blob/f4d509ffd07434d36e58a7df5b983188db3fdfa1/hooks/post-up#L6). 

I've opened https://github.com/thoughtbot/dotfiles/pull/543 to add a bit of detail around updating to the README.
