### ISSUE TITLE
Changing EDITOR env to nvim

### ISSUE THREAD

**Issue by StevenXL** [thoughtbot/dotfiles#546]
Hi folks. Thank you very much for this project. 

I don't believe this is an issue with the project, just a mis-understanding on my part on how all the pieces fit together. 

My goal is to change the EDITOR env variable to nvim. I can see that this is set in `dotfiles/zsh/configs/editor.zsh` to `$VISUAL`, and `VISUAL` is set in that same file to `vim`.

Based off the directions in the README, I added the following contents to `~/dotfiles-local/zsh/configs/editor.zsh`:

```text
export VISUAL=nvim
export EDITOR=$VISUAL
```

But that did not work. (I tried originally to name the file `editor.zsh.local` just to follow the directions as robotically as possible). 

The odd thing is that I also wanted to change my `HISTSIZE` and `SAVEHIST` to 10_000, and that worked if I added that to `~/dotfiles-local/zsh/configs/history.zsh`. But I might be doing that wrong as it only takes affect after starting tmux. 

Thank you for any help.

P.S. If there is a more appropriate place to ask for help with this, please let me know. As I said, I don't think this is an issue with the project itself.

**Comment by geoffharcourt** [comment]
Hi! Are you using `rcm`? The easiest way to do this would be to make your `editor.zsh` file in your `dotfiles-local` have those two lines, and then your local dotfiles will "win" when rcm builds symlinks.

This is how I do it for my personal configuration, you can check it out here:
https://github.com/geoffharcourt/dotfiles-local/blob/98cd9cd01781ca05b8c051aa73d6de1897ce87e9/zsh/configs/editor.zsh
