### ISSUE TITLE
w0rp ale issues with erb files

### ISSUE THREAD

**Issue by fernandoaleman** [thoughtbot/dotfiles#556]
Has anyone experienced any issues with syntax on .erb files using `w0rp/ale`? I started experiencing this issue today upon updating my `dotfiles` and see that there is already an issue open in their repo. https://github.com/w0rp/ale/issues/580

Here is a screenshot that shows a blank .erb file open with the error. Wondering if anyone has come across this issue and has a fix.

![screenshot 2017-10-19 15 53 28](https://user-images.githubusercontent.com/523634/31793741-b2562774-b4e5-11e7-8650-396a743686d3.png)

**Comment by geoffharcourt** [comment]
Related: https://github.com/w0rp/ale/issues/580

**Comment by geoffharcourt** [comment]
I want to reopen this and consider solutions in the event the ALE maintainers don't finalize their solution soon.

**Comment by sublimecoder** [comment]
I have this same issue. Very annoying. It'd be great if we could get this pull request merged.

**Comment by geoffharcourt** [comment]
ALE made a change in w0rp/ale#580 that I believe should resolve this issue.
