### ISSUE TITLE
git-merge-branch shouldn't exit with success if merge failed

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/dotfiles#563]
Noticed this where I was trying to merge something and push:

`git merge-branch && git push origin` changed branch to master but didn't push.

Maybe we should change back to the original branch if we fail?

**Comment by croaky** [comment]
Or maybe something like:

```sh
git fetch origin
line_count=$(git diff origin/master..master | wc -l)

if [ $line_count -gt 0 ]; then
  printf "master is not up to date with origin/master"
else
  git checkout master
  git merge "@{-1}"
fi
```
