### ISSUE TITLE
SILENCE_RBENV_DEPRECATION not working?

### ISSUE THREAD

**Issue by jessieay** [thoughtbot/dotfiles#567]
per https://github.com/thoughtbot/dotfiles/blob/346268b6e71e832836eaecc16404494908badcb8/zsh/configs/post/path.zsh

I am trying to add `SILENCE_RBENV_DEPRECATION` to my config. I added `export SILENCE_RBENV_DEPRECATION=1` in my `dotfiles-local/zshrc.local` and ran `rcup` and it appears to install in the correct location. But, I am still seeing this deprecation error. Help!

**Comment by jessieay** [comment]
On a related note, I tried to start using `asdf` last weekend but could only get it to work properly when I commented out the conditional in `zsh/configs/post/path.zsh` -- with the conditional in place, `which ruby` was returning system ruby.

**Comment by geoffharcourt** [comment]
@jessieay I wonder if this is a source-order issue? Could you put that declaration in `zsh/configs/pre/rbenv.zsh` and see if it resolves the issue?

**Comment by bengolder** [comment]
That worked great!

1. Made the `~/dotfiles/zsh/config/pre` directory
2. Added `rbenv.zsh` containing `export SILENCE_RBENV_DEPRECATION=1`
3. Re-ran `rcup`
4. Started some new terminals and the warning was gone!

**Comment by geoffharcourt** [comment]
@jessieay can you LMK if you still have issues? If you've moved on to ALE this might no longer be relevant to dotfiles.

**Comment by jessieay** [comment]
oh yes! I was writing this on behalf of @bengolder last time because we were pairing / getting his machine setup. All good now :)
