### ISSUE TITLE
Considered using splitjoin vim plugin?

### ISSUE THREAD

**Issue by jessieay** [thoughtbot/dotfiles#574]
I just started using the splitjoin vim plugin and it is making my life much better. https://github.com/AndrewRadev/splitjoin.vim

The automatic wrapping at 80 chars is great when I am writing markdown, but in Ruby I have always been manually updating my linebreaks. On top of that, Rubocop autocorrect cannot fix my linebreaks for me. Too much manual work!

If this vim plugin were to be added to the dotfiles, we'd probably want to add some customizations. For example, I set:

```
let g:splitjoin_trailing_comma = 1   
let g:splitjoin_ruby_curly_braces = 0
```

in my vimrc so that it automatically includes trailing commas and does not include redundant hash parameters.

If people are into this idea, I'd be happy to submit a PR! Just thought I'd check first. Or, of it's not dotfiles material, I hope some people try it out because it's really saving me a ton of time!

**Comment by gylaz** [comment]
I use the plugin too, primarily for quickly splitting up arguments when line gets over 80 chars.
I also set:
```
let g:splitjoin_ruby_hanging_args = 0
```
I think this plugin would be useful to other thoughtbotters, but I'm not sure how discoverable the value of the plugin would be.

**Comment by geoffharcourt** [comment]
My last experiment with splitjoin was frustrating, but I'm putting it on my list of things to use more often in the next month.

**Comment by geoffharcourt** [comment]
i think we don't have enough consensus to make this a shared change. I'm going to close, but we can reopen if there's a groundswell of support.

**Comment by jessieay** [comment]
Makes sense, thanks for the update @geoffharcourt
