### ISSUE TITLE
Homebrew install of asdf throws missing file error

### ISSUE THREAD

**Issue by dcalhoun** [thoughtbot/dotfiles#577]
After seeing the [deprecation prompt](https://github.com/thoughtbot/dotfiles/pull/534/files#diff-86825654719a40b2eb1921da73a31efaR9), I decided to replace `rbenv` with `asdf`.

I installed `asdf` via homebrew, which appears to have worked just fine. Executing `asdf` commands via the CLI works. However, each shell window I open, the thoughtbot dotfiles output the following error.

```
/Users/username/.zsh/configs/post/path.zsh:.:6: no such file or directory: /Users/username/.asdf/asdf.sh
```

```bash
❯ which asdf
/usr/local/opt/asdf/bin/asdf
```

### Environment

* macOS 10.13.2
* asdf 0.4.1
* zsh 5.3

**Comment by geoffharcourt** [comment]
Hi, a few questions:

- What's in your `$HOME/.asdf` directory? 
- Is that `username` you added a redaction of the actual username that was output?
- did you install asdf to a non-standard location?


I think there may be a problem with your asdf installation, that script looks like it's the equivalent of `rbenv init`, and asdf expects it to be there when the shell starts.

**Comment by dcalhoun** [comment]
* `$HOME/.asdf` contains only `installs/ruby`, which I created manually [per the migration guides](https://github.com/asdf-vm/asdf-ruby/tree/3030b44672951804100fbd2e36b4768ca31211e0#rbenv).
* Yes, `username` is merely a redaction of the system's actual user name.
* I installed `asdf` using Homebrew. So, no I would not consider it non-standard. It is located in `/usr/local/Cellar` alongside all my other Homebrew installed package.

If you believe this is an `asdf` issue and not related to this project, I can open an issue under `asdf`. I perceived it as an issue specific to `thoughtbot/dotfiles`, as the error came from within [a dotfile](https://github.com/thoughtbot/dotfiles/blob/0786549686a63f7d808581d559821ec30277ed21/zsh/configs/post/path.zsh#L6). I could understand how this is not related to `thoughtbot/dotfiles`, though.

**Comment by dcalhoun** [comment]
Here is two additional pieces of information.

1. Even though I "migrated" my installed rubies from rbenv, `asdf ruby list` returns the following.
```bash
❯ asdf list ruby
No versions installed
```

2. Running `brew info asdf` returns the following.

```
❯ brew info asdf
asdf: stable 0.4.1
Extendable version manager with support for Ruby, Node.js, Erlang & more
https://github.com/asdf-vm
/usr/local/Cellar/asdf/0.4.1 (91 files, 178.5KB) *
  Built from source on 2017-12-27 at 08:19:12
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/asdf.rb
==> Dependencies
Required: autoconf ✔, automake ✔, libtool ✔, coreutils ✔, libyaml ✔, openssl ✔, readline ✔, unixodbc ✔
==> Caveats
Add the following line to your bash profile (e.g. ~/.bashrc, ~/.profile, or ~/.bash_profile)
     source /usr/local/opt/asdf/asdf.sh

If you use Fish shell, add the following line to your fish config (e.g. ~/.config/fish/config.fish)
     source /usr/local/opt/asdf/asdf.fish

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```

I did add `source /usr/local/opt/asdf/asdf.sh` to my dotfile extensions, which is why I have access to the `asdf` CLI.

I attempted symlinking the above the `$HOME/.asdf/asdf.sh`, but the creates a new set of errors on shell creation.

```
/Users/username/.asdf/asdf.sh:source:4: no such file or directory: /Users/username/lib/utils.sh
/Users/username/.asdf/asdf.sh:source:7: no such file or directory: /Users/username/lib/commands/help.sh
/Users/username/.asdf/asdf.sh:source:9: no such file or directory: /Users/username/lib/commands/update.sh
/Users/username/.asdf/asdf.sh:source:11: no such file or directory: /Users/username/lib/commands/install.sh
/Users/username/.asdf/asdf.sh:source:13: no such file or directory: /Users/username/lib/commands/uninstall.sh
/Users/username/.asdf/asdf.sh:source:15: no such file or directory: /Users/username/lib/commands/current.sh
/Users/username/.asdf/asdf.sh:source:17: no such file or directory: /Users/username/lib/commands/where.sh
/Users/username/.asdf/asdf.sh:source:19: no such file or directory: /Users/username/lib/commands/which.sh
/Users/username/.asdf/asdf.sh:source:21: no such file or directory: /Users/username/lib/commands/version_commands.sh
/Users/username/.asdf/asdf.sh:source:23: no such file or directory: /Users/username/lib/commands/list.sh
/Users/username/.asdf/asdf.sh:source:25: no such file or directory: /Users/username/lib/commands/list-all.sh
/Users/username/.asdf/asdf.sh:source:27: no such file or directory: /Users/username/lib/commands/reshim.sh
/Users/username/.asdf/asdf.sh:source:29: no such file or directory: /Users/username/lib/commands/plugin-add.sh
/Users/username/.asdf/asdf.sh:source:31: no such file or directory: /Users/username/lib/commands/plugin-list.sh
/Users/username/.asdf/asdf.sh:source:33: no such file or directory: /Users/username/lib/commands/plugin-list-all.sh
/Users/username/.asdf/asdf.sh:source:35: no such file or directory: /Users/username/lib/commands/plugin-update.sh
/Users/username/.asdf/asdf.sh:source:37: no such file or directory: /Users/username/lib/commands/plugin-remove.sh
/Users/username/.asdf/asdf.sh:source:40: no such file or directory: /Users/username/lib/commands/plugin-push.sh
/Users/username/.asdf/asdf.sh:source:42: no such file or directory: /Users/username/lib/commands/plugin-test.sh
/Users/username/.asdf/asdf.sh:115: command not found: help_command
```

**Comment by rjdellecese** [comment]
@dcalhoun, I'd say your installation directory is non-standard, per the installation instructions in the asdf README (https://github.com/asdf-vm/asdf#setup).

**Comment by dcalhoun** [comment]
@rjdellecese fair enough.

**Comment by geoffharcourt** [comment]
@dcalhoun as our dotfiles are configured, [we expect your ASDF install to be in `$HOME/.asdf`](https://github.com/thoughtbot/dotfiles/blob/0786549686a63f7d808581d559821ec30277ed21/zsh/configs/post/path.zsh#L5-L6). If asdf has some utility that will return the location where it's installed instead (something like `brew prefix`) then I'd be open to a PR to make this more flexible. Otherwise I think you'll have to resolve this by adding your own personal customization to replace `zsh/configs/post/path.zsh`.

**Comment by dcalhoun** [comment]
For posterity, I was able to suppress the missing file warning with the following symlink. It's brittle, as it will break with any upgrade of `asdf` via Homebrew, but it works as a short-term fix.

```
ln -s /usr/local/Cellar/asdf/0.4.1/asdf.sh ~/.asdf/asdf.sh
```

Hopefully I arrive at a long-term solution at some point.

**Comment by 0xdevalias** [comment]
@dcalhoun Bit old, but since google lead me here, this is how I resolved it for myself:

In one of my zsh 'loading' files:
```
export ASDF_DATA_DIR=`brew --prefix asdf`
source $ASDF_DATA_DIR/asdf.sh
source $ASDF_DATA_DIR/completions/asdf.bash
```

Ref: https://asdf-vm.com/#/core-configuration?id=environment-variables

**Comment by dcalhoun** [comment]
@0xdevalias thanks!

**Comment by wesmcnamee-avalara** [comment]
Not entirely sure why this is closed. I ran into the same problem.

```
brew install asdf
```

but `$HOME/.asdf` was not created

**Comment by dcalhoun** [comment]
@wesmcnamee-avalara it is closed because thoughtbot has a stance on how asdf should be installed. I presume you attempted the solution outlined by @0xdevalias above?

**Comment by rjdellecese** [comment]
There's actually an open PR now (https://github.com/thoughtbot/dotfiles/pull/629) that addresses this for Homebrew asdf installs. Maybe it should be informed by @0xdevalias's comment above, though (https://github.com/thoughtbot/dotfiles/issues/577#issuecomment-466609761)?

**Comment by almouattaz** [comment]
I had the same issue, where suddenly the commands: erl, erlang and iex where not working.
This hapenned after a Homebrew install. [Homebrew lauched an automatic update while I was trying to install a new program 😭]
I noticed that all my asdf shim files changed their asdf version to 0.8.1_1 while the version I had before the homebrew update was 0.11.0
Fortunately, the path to my 0.11.0 was still present on my file system 🍀.
Theses are the errors I was getting:
`
/Users/almouattaz/.asdf/shims/iex: line 5: /usr/local/Cellar/asdf/0.8.1_1/libexec/bin/asdf: No such file or directory
/Users/almouattaz/.asdf/shims/iex: line 5: exec: /usr/local/Cellar/asdf/0.8.1_1/libexec/bin/asdf: cannot execute: No such file or directory
`
For each of theses programs (erl, erlang and iex) I went to the corresponding file and corrected the path that was pointing to the bad version 0.8.1_1

No I can run iex again 😊

So, if you had the same problem, I recommend that you check the files in the errors, do call non existant paths, make a back-ip of those files and correct them.

**Comment by Tovrik** [comment]
For what it's worth, running `asdf reshim` seems to fix this problem for me.

**Comment by sergey-chechaev** [comment]
Try echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ~/.zshrc

**Comment by rohanmahy** [comment]
> [@dcalhoun](https://github.com/dcalhoun) Bit old, but since google lead me here, this is how I resolved it for myself:
> 
> In one of my zsh 'loading' files:
> 
> ```
> export ASDF_DATA_DIR=`brew --prefix asdf`/

I installed asdf a moment ago. asdf.sh is now in `/opt/homebrew/opt/asdf/libexec` , so this "fix" no longer works.

Even after fixing the broken default directories, following the basic instructions, and liberally running `asdf reshim`, I am still getting the same version errors.

until one can do a clean install using `brew install asdf && asdf plugin add python && asdf install python latest` or somesuch,, and this runs regularly in the CI, I personally don't consider `asdf` ready for primetime on macOS.

> source $ASDF_DATA_DIR/asdf.sh
> ```
> 
> Ref:
> 
> * https://asdf-vm.com/#/core-configuration?id=environment-variables
> * [0xdevalias/dotfiles@6405bd6](https://github.com/0xdevalias/dotfiles/commit/6405bd6781115599ff2a3c3f6f71e9d25c28b3d5)
