### ISSUE TITLE
typo of readme and add of chmod

### ISSUE THREAD

**Issue by inaling** [thoughtbot/dotfiles#583]
Is not it necessary to fix the following 2 points?

1. Is not ``~/dotfiles`` rather than ``~/.dotfiles`` ?
> git clone git://github.com/thoughtbot/dotfiles.git ~/dotfiles
> env RCRC=$HOME/dotfiles/rcrc rcup

2. Before executing rcup, add description of chmod
>  chmod -R +x ~/.dotfiles/hooks

In order to run rcup as expected, we had to deal with both.

**Comment by geoffharcourt** [comment]
Hi @17ringe, the recommended location for these dotfiles is not a typo. `rcup` symlinks those files into dotted (?) locations. You are of course welcome to use your own location, but you'll want to add your own `rcrc` file in your personal customizations (or always run `rcup` with the `env RCRC=` prefix.

**Comment by 17ringe** [comment]
@georgebrock Thank you for reply. I understand.
