### ISSUE TITLE
Undefined variable: g:has_async

### ISSUE THREAD

**Issue by ll931217** [thoughtbot/dotfiles#589]
Hello, I am new to using VIM and trying out your `~/vimrc` since it was suggested to me by a speaker from one of the Thoughtbot conferences. After copying the contents of your vim file, I keep getting this error. I Googled it to find out what it was, so I installed the ALE plugin through Pathogen, but still not working. I checked with `:scriptnames` to see if the plugin was installed and indeed, it was. The only thing I could think of is that maybe it should be called something else instead of `g:has_async`?

**Comment by mikegee** [comment]
`g:has_async` is defined in [`vimrc.bundles`](https://github.com/thoughtbot/dotfiles/blob/21055dff633feea87bc9526efb5b2fcc04bc025e/vimrc.bundles#L13)

I think that using just part of these dotfiles and not installing them as described in the README is bound to lead to trouble like this.

**Comment by geoffharcourt** [comment]
Hi @ll931217 If you want to pick and choose from the files, you'll probably have to do some commenting out of lines like that, as they are meant to be used as a set (or for ideas to extract yourself).
