### ISSUE TITLE
zsh/completion/_rspec doesn't take into account of --default-path being set to something not 'spec'

### ISSUE THREAD

**Issue by dcatt-haiku** [thoughtbot/dotfiles#593]
The ZSH autocomplete logic assumes that 'spec' is the default path for where tests live when in some cases can be overridden with the --default-path setting it to something else more meaningful.  Would be great if the autocomplete logic would check the .rspec config file and see if the --default-path has been set and use its value for autocompleting the test directory when 'spec' is not in play.

**Comment by geoffharcourt** [comment]
HI @dcatt-haiku this sounds like a nice feature, but I worry that it might be slow if we have to parse the RSpec config on each tab completion attempt. If there's a PR that can show a solution to this problem that doesn't have a big latency hit, we can look at merging it.
