### ISSUE TITLE
New universal ctags configuration location.

### ISSUE THREAD

**Issue by sublimecoder** [thoughtbot/dotfiles#599]
Universal-ctags has updated their config location. 

Instead of using $HOME/.ctags they now use $HOME/.ctags.d/*.ctags

**Example:**
$HOME/.ctags.d/config.ctags

**Comment by geoffharcourt** [comment]
I think most tb-ers are using Exuberant Ctags, not Universal Ctags, which is probably why this hasn't been noticed until now. @sublimecoder if you want to put up a PR to merge a ctags config for Universal Ctags in the right spot, please do!
