### ISSUE TITLE
Backing up local dotfile customizations

### ISSUE THREAD

**Issue by jacobsmith** [thoughtbot/dotfiles#604]
Hello,

I've got a few aliases, vim configs, etc. that I currently have at `~/.aliases.local` and `~/.vimrc.local` so that the `~/.zshrc` file will load them. I've tried putting them in `~/dotfiles-local` but they don't seem to load from there. I'm not sure if I'm doing something in correctly or if there is an issue with the library.

My end goal is to be able to have all of my customizations to dotfiles in a git repo that I can have backed up and restore easily on a new computer. Any advice as to the `~/dotfiles-local` directory or how that should be set up would be appreciated!

**Comment by anhari** [comment]
Are you using [rcm](https://github.com/thoughtbot/rcm) to generate symlinks for your `~/dotfiles-local` directory?

The [rcrc](https://github.com/thoughtbot/dotfiles/blob/master/rcrc) file sets `~/dotfiles-local` as a directory to use during `rcup`.

**Comment by geoffharcourt** [comment]
HI, `rcm` is our recommended solution for combining your own customizations from a personal repository with our shared configuration. Check out the basic instructions [here](https://github.com/thoughtbot/dotfiles#install) and also see the [rcm docs](https://github.com/thoughtbot/rcm).

**Comment by jacobsmith** [comment]
I don't think I tried doing `rcup` after putting them in the `~/dotfiles-local` folder (I thought the `.zshrc` would automatically look there). Thanks for the tip!
