### ISSUE TITLE
zshrc function _load_settings raise error

### ISSUE THREAD

**Issue by uybinh** [thoughtbot/dotfiles#606]
After I created `pre` and `post` folder in `~/dotfiles-local/zsh/configs`
When open new shell, it shows
```
_load_settings:5: parse error: condition expected: =
```
Is there anything wrong with my configs?

**Comment by uybinh** [comment]
so file in `pre` and `post` folder must have `.zsh` extension?

**Comment by monsonjeremy** [comment]
Did you find a solution to this @uybinh?
