### ISSUE TITLE
How to deactivate Ale?

### ISSUE THREAD

**Issue by ashwinvidiyala** [thoughtbot/dotfiles#607]
I have spent hours on this, and I can't seem to figure out how to override the Ale defaults in the `vimrc` files that comes with the thoughtbot dotfiles. I don't want asynchronous linting.

I essentially want to deactivate these ([source](https://github.com/thoughtbot/dotfiles/blob/master/vimrc#L47-L57)):
```
  " ALE linting events
  if g:has_async
    set updatetime=1000
    let g:ale_lint_on_text_changed = 0
    autocmd CursorHold * call ale#Lint()
    autocmd CursorHoldI * call ale#Lint()
    autocmd InsertEnter * call ale#Lint()
    autocmd InsertLeave * call ale#Lint()
  else
    echoerr "The thoughtbot dotfiles require NeoVim or Vim 8"
  endif
```

Either that or I want to be able to remove a plugin from the `vimrc.bundles`. But I don't know how to uninstall a plugin that's in the `vimrc.bundles` through my `vimrc.bundles.local` file.

**Comment by geoffharcourt** [comment]
Hi! 

Try
`UnPlug 'ale'`

in your `vimrc.bundles.local` file to avoid installing ALE.

**Comment by ashwinvidiyala** [comment]
Now it's upset because there are references to it in the `vimrc` files.

How do I nullify this keybinding in my local file: `autocmd CursorHold * call ale#Lint()`?
That'll give me an idea on changing/removing the other ones.

Thanks a lot by the way for the help!

**Comment by christoomey** [comment]
Hi @ashwinvidiyala, unfortunately I don't think our current implementation is amenable to that. That said, I think it would be relatively straightforward to wrap the `autocmd`s in an `augroup` in this dotfiles repo, and the you would be able to call `augroup! ALE` or similar in your vimrc.local (in addition to the `UnPlug` Geoff referenced). See `:h augroup` for details. We'd certainly be open to a PR that makes the `augroup` change if that did indeed provide a path forward for you.

**Comment by ashwinvidiyala** [comment]
@christoomey Thank you.

So I extracted out `ALE`'s settings into its own `augroup` in the `vimrc` file:

```
" ALE linting events
augroup ale
  autocmd!

  if g:has_async
    set updatetime=1000
    let g:ale_lint_on_text_changed = 0
    autocmd CursorHold * call ale#Lint()
    autocmd CursorHoldI * call ale#Lint()
    autocmd InsertEnter * call ale#Lint()
    autocmd InsertLeave * call ale#Lint()
  else
    echoerr "The thoughtbot dotfiles require NeoVim or Vim 8"
  endif
augroup END
```

And this is what I have in my `vimrc.local`:
```
augroup ale
  autocmd!

  let g:ale_lint_on_text_changed = 0
  let g:ale_lint_on_enter = 0
augroup END
```
And I also have this line in my `vimrc.bundles.local`:
`UnPlug 'w0rp/ale'`

It's still not turning off `ALE`. I was almost certain that this approach would work. Am I doing something wrong?

@christoomey I couldn't use `augroup! ale` as you suggested because it was throwing an error. This is what `:h augroup!` says about `augroup!`:
```
                                                 :augroup-delete E367 W19 E936
:aug[roup]! {name}              Delete the autocmd group {name}.  Don't use
                                this if there is still an autocommand using
                                this group!  You will get a warning if doing
                                it anyway. when the group is the current group
                                you will get error E936.
```

**Comment by ashwinvidiyala** [comment]
[Here's the PR](https://github.com/thoughtbot/dotfiles/pull/608).

**Comment by geoffharcourt** [comment]
@ashwinvidiyala I think you'll need to run `:PlugClean` to remove ALE with `UnPlug` if that's what you're hoping to do. I just reviewed your PR and I think it looks good to go, just waiting for another reviewer before we merge.

**Comment by ashwinvidiyala** [comment]
@geoffharcourt I think that may have actually worked. Sweet! Thanks :)

**Comment by geoffharcourt** [comment]
Closing now that 695d92f is merged.
