### ISSUE TITLE
Customized the prompt symbol

### ISSUE THREAD

**Issue by iamajvillalobos** [thoughtbot/dotfiles#611]
Is it possible to only customized the prompt symbol like https://github.com/sindresorhus/pure? I like how it currently looks and works but sometimes I want to spice things up and change the `%` to maybe `$`.

**Comment by geoffharcourt** [comment]
Hi, you can override the `PS1` variable to set the prompt to be whatever you want it to be:

Make a `prompt.zsh` file in your dotfiles-local:
https://github.com/thoughtbot/dotfiles/blob/master/zsh/configs/prompt.zsh
