### ISSUE TITLE
ale#Lint is not a function.

### ISSUE THREAD

**Issue by StevenXL** [thoughtbot/dotfiles#616]
Hi Folks,

I usually use the thoughtbot dotfiles on a mac, but I am trying to use them on a Ubuntu 18.04 machine.

Things work pretty smoothly, but I am getting an issue with Ale:

```
Error detected while processing CursorHold Auto commands for "*":
E117: Unknown function: ale#Lint
```

**Comment by theasteve** [comment]
@StevenXL I get the same error on MacOS High Sierra.

**Comment by StevenXL** [comment]
@theasteve I'm on Mojave and like I said above, getting on Ubuntu as well.

**Comment by eebs** [comment]
@StevenXL, @theasteve, there's some more discussion in https://github.com/thoughtbot/dotfiles/pull/615. Looks like a solution will be available shortly, or if you need the fix now you can follow the advise in the PR.

**Comment by StevenXL** [comment]
@eebs thank you! I'll keep an eye out for the fix; in the meantime, it's not (just) my machine, and I can disable ale until that issue is closed.
