### ISSUE TITLE
Is there a way to do this for ubuntu ?

### ISSUE THREAD

**Issue by Awalvie** [thoughtbot/dotfiles#621]
I was told about the thoughbot dotfiles from a friend and wanted to try them out since I am a beginner but I am currently on a linux machine and this does not seem to be working for me. 
Is there a version for linux (specifically ubuntu) that I could use to get started with dotfiles ?

**Comment by ZethJack** [comment]
Not entirely sure what you are trying to accomplish, as the README file seems self explanatory: All you need to do is to open up the terminal (Ubuntu has keyboard shortcut `ctrl + alt + T`) and then follow instructions:
* Set zsh as your shell with `chsh -s $(which zsh)`
* clone dotfiles repository `git clone git://github.com/thoughtbot/dotfiles.git ~/dotfiles`
* Install **rcm** `sudo apt-get install rcm`
* Install the dotfiles `env RCRC=$HOME/dotfiles/rcrc rcup`

**Comment by Awalvie** [comment]
Oh I was trying to install this using brew for linux. Maybe that is causing the problem. I'll try it with sudo and let you know if it works.

**Comment by ZethJack** [comment]
Oh I see.
`brew` is actually meant for OSX users,
Guess nobody thought of having to mention that you are supposed to install RCM via whatever method your distro actually uses:
> **macOS with Homebrew:**
> brew tap thoughtbot/formulae
> brew install rcm
> **macOS with MacPorts:**
> port install rcm
> **OpenBSD:**
> doas pkg_add rcm
> openSUSE/RHEL/CentOS: instructions
> **Ubuntu:**
> sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm
> sudo apt-get update
> sudo apt-get install rcm
> **Void Linux:**
> sudo xbps-install -S rcm
> **Elsewhere:**
> This uses the standard GNU autotools, so it's the normal dance:
> curl -LO https://thoughtbot.github.io/rcm/dist/rcm-1.3.3.tar.gz &&
> sha=$(sha256 rcm-1.3.3.tar.gz | cut -f1 -d' ') &&
> [ "$sha" = "935524456f2291afa36ef815e68f1ab4a37a4ed6f0f144b7de7fb270733e13af" ] &&
> tar -xvf rcm-1.3.3.tar.gz &&
> cd rcm-1.3.3 &&
> ./configure &&
> make &&
> sudo make install

**Comment by Awalvie** [comment]
Yep that did the trick thanks.
