### ISSUE TITLE
Case INsensitive cd

### ISSUE THREAD

**Issue by lgomez** [thoughtbot/dotfiles#630]
Hi all,

I recently moved from OMZ to your dotfiles to hopefully simplify my setup but there is one thing I have not been able to do: make `cd` case INsensitive with completions. Is there a recommended way to do this? I even went into OMZ to try to get it done the way they do it but no luck. I'm on OSX Mojave. Any ideas?

Thank you

**Comment by geoffharcourt** [comment]
Hi, I suspect doing this would require overriding zsh's `cd` built-in and replacing it with another function, which is generally outside the scope of what I think we'd want to do here in dotfiles. If you figure out how to do this, I'd be curious to see if there's a relatively performant way.
