### ISSUE TITLE
vim-fugitive warning when ctags found within .git directory

### ISSUE THREAD

**Issue by andyw8** [thoughtbot/dotfiles#650]
There was a [recent change](https://github.com/tpope/vim-fugitive/commit/63a05a6935ec4a45551bf141089c13d5671202a1) to vim-fugitive that seems to be conflicting with how the [ctags git hook](https://github.com/thoughtbot/dotfiles/blob/master/git_template/hooks/ctags) works.

I'm not sure if this has always been the case, but the hook is creating a `tags` file within the `.git` directory of the repo. When vim starts, vim-fugitive emits a warning:

```
Fugitive .git/tags support removed in favor of `:set tags^=./.git/tags;`
```

(Note: For some reason, I had to first disable some custom vim config, otherwise there was a prompt, but the message wasn't visible). 

The warning goes away when I add `set tags^=./.git/tags` to my `.vimrc`, but it seems Fugitive is trying to discourage this practice (there are some reasons from tpope in the PR).

**Comment by eebs** [comment]
I believe this was addressed in https://github.com/thoughtbot/dotfiles/pull/641. Are you up to date with `master`?

**Comment by andyw8** [comment]
Ah, yes I was out out of date, thanks.
