### ISSUE TITLE
gitignore.local being ignored?

### ISSUE THREAD

**Issue by StevenXL** [thoughtbot/dotfiles#665]
Hi folks,

Following the directions in the README, I added the following file: `/Users/stevenleiva/dotfiles-local/gitignore.local` with the following content:

```
.envrc
```

However, even after running `rcup`, `.envrc` files are **not** being ignored by git in other repositories.

**Comment by mikegee** [comment]
You may need to run

```
git config --global core.excludesfile ~/.gitignore_global
```

https://help.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

**Comment by StevenXL** [comment]
@mikegee I somehow missed your comment. I can't claim to have fixed this issue, but I have not ran into the problem again. I will close this for now, and re-open if I run into it again.
