### ISSUE TITLE
`git up` now rebases against `master` and not `origin/master`

### ISSUE THREAD

**Issue by purinkle** [thoughtbot/dotfiles#671]
Before #667, `git up` used to fetch the remote and rebase against `origin/master`.

Now that we are supporting a flexible trunk branch name, it seems that we rebase against `master` instead.

**Comment by geoffharcourt** [comment]
@purinkle good spot! Fixing that now.

**Comment by geoffharcourt** [comment]
I thought this was something broken on my setup. Thanks for finding! https://github.com/thoughtbot/dotfiles/pull/672
