### ISSUE TITLE
Ctags warnings

### ISSUE THREAD

**Issue by jessieay** [thoughtbot/dotfiles#674]
I am using these dotfiles with just a few additional configs. 

I am trying to get my ctags set up. When I run `ctags` in the command line, I get the following output:

```
% ctags
ctags: Warning: Don't reuse the kind letter `A' in a language Ruby (old: "accessor", new: "attr")
ctags: Language "Elixir" already defined
```

I have [universal-ctags installed via homebrew[https://github.com/universal-ctags/homebrew-universal-ctags) and those are the ctags being used:

```
% which ctags
/usr/local/bin/ctags
```

I think this is coming from https://github.com/thoughtbot/dotfiles/blob/2e3d643c54120b02940d1f654c4962a945304e89/ctags.d/config.ctags#L2 because when I remove the Ruby/Elixir configs in there the error goes away. The error message doesn't pull up anything relevant with googling.

I wonder if this is leading to my ctags to not generate properly because when I run `<leader>ct` in Vim, I get `E73: tag stack empty` 

Is this error specific to my machine?

**Comment by geoffharcourt** [comment]
@jessieay the Ruby warning is a known, not-yet-fixed issue in universal-ctags:
https://github.com/universal-ctags/ctags/issues/1228

**Comment by jessieay** [comment]
@geoffharcourt nice, I actually say that thread but didn't realize it was the same error I was seeing.

Does this have anything to do with the fact that my ctags list is empty? I must admit that I am not super familiar with ctags but as far as I can tell they are not generating.

**Comment by geoffharcourt** [comment]
I'm afraid I cant' be much help here. After a lot of struggling with ctags I gave up and have been using LSP with Typescript and Ruby. I've found it's a better experience when I want to dive into dependencies, but it comes with its own set of problems.

**Comment by natejonesyello** [comment]
@joshuaclayton Any insight here? 

As far as I can tell these warnings are preventing ctag generation in Rails apps, rendering [unused](https://github.com/unused-code/unused) ... unusable (ba-dum ch).

Is there a good alternative we can use instead?

**Comment by joshuaclayton** [comment]
@natejonesyello I have my own version of dotfiles rather than this repo, so I can't speak to the configuration here directly.

I would say that the combination of [universal ctags](https://ctags.io/) and using `git ls-files` to generate the list of files to run ctags against has meant that most/all of the `--exclude` settings are probably unnecessary, as are some of the language-specific overrides (since universal ctags supports more languages out of the gate), including this Ruby one most likely.

My guess? If possible, nuke/move the ctags config, and see if that addresses the issue.

**Comment by CodingFu** [comment]
I used 

```
brew install ctags
brew link --force ctags
```

on my OS X and it works now!

```
[I] ➜ ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan 24 2021, 03:39:33
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```

this is what I see in my terminal when I test it. before it `ctags --version` just showed me 2 errors above

**Comment by hiattp** [comment]
Not sure if https://github.com/thoughtbot/dotfiles/pull/684 fixes this entirely (it might just be sidestepping the issue with universal-ctags mentioned by @geoffharcourt [above](https://github.com/thoughtbot/dotfiles/issues/674#issuecomment-647715339)) but it at least allows ctags to generate and makes https://github.com/universal-ctags/ctags/issues/1228 a lesser issue. Thoughts on getting #684 merged?
