### ISSUE TITLE
New location for fzf under macOS with ARM architecture

### ISSUE THREAD

**Issue by fievelk** [thoughtbot/dotfiles#681]
On macOS with M1 chip, Homebrew is now installed by default in `/opt/homebrew/` (see https://github.com/Homebrew/install/pull/373).

The current installation process determines whether fzf was installed via Homebrew, but only checks under `/usr/local/`: https://github.com/thoughtbot/dotfiles/blob/2a59c1890f81bffc1db79cae4482ce2b706b0f79/vimrc.bundles#L20-L26

I think adding a new check for `/opt/homebrew/` might help for machines with M1 chips.

**Comment by marcelosalloum** [comment]
You can solve it by adding `export FZF_BASE="/opt/homebrew/opt/fzf"` to your bash file.
