### ISSUE TITLE
Weird text when I open vim

### ISSUE THREAD

**Issue by iamajvillalobos** [thoughtbot/dotfiles#694]
I freshly installed the dotfiles and I'm getting this when I open my vim.

![CleanShot 2022-01-31 at 00 23 15@2x](https://user-images.githubusercontent.com/7567758/151707940-05c307d3-c886-4a85-8c1f-99c1131cef32.png)

OS Info:
![CleanShot 2022-01-31 at 00 24 17@2x](https://user-images.githubusercontent.com/7567758/151707960-16991287-3513-4781-933a-30dd0cccd528.png)

**Comment by danielnolan** [comment]
@ iamajvillalobos is this still an issue for you? We have made some updates that add better support for Macs with Apple silicon.

**Comment by iamajvillalobos** [comment]
Installed on a fresh macbook pro m2 and don't encounter it anymore

<img width="1550" alt="Screenshot 2023-06-09 at 1 21 57 AM" src="https://github.com/thoughtbot/dotfiles/assets/7567758/413e9907-68f5-4d90-b8a3-7021701a27e6">
