### ISSUE TITLE
Outdated gitconfig explanation in README?

### ISSUE THREAD

**Issue by dorianmariefr** [thoughtbot/dotfiles#696]
In the README it says:

> * Adds a `create-branch` alias to create feature branches.
> * Adds a `delete-branch` alias to delete feature branches.
> * Adds a `merge-branch` alias to merge feature branches into master.
> * Adds an `up` alias to fetch and rebase `origin/master` into the feature branch. Use `git up -i` for interactive rebases.
> * Adds `post-{checkout,commit,merge}` hooks to re-index your ctags.
> * Adds `pre-commit` and `prepare-commit-msg` stubs that delegate to your local
>   config.
> * Adds `trust-bin` alias to append a project's `bin/` directory to `$PATH`.

But this is what is in the `.gitconfig`:

```gitconfig
[alias]
  aa = add --all
  ap = add --patch
  branches = for-each-ref --sort=-committerdate --format=\"%(color:blue)%(authordate:relative)\t%(color:red)%(authorname)\t%(color:white)%(color:bold)%(refname:short)\" refs/remotes
  ci = commit -v
  co = checkout
  pf = push --force-with-lease
  st = status
```

**Comment by jferris** [comment]
Those Git aliases are in the `bin` directory. If you have an executable on your path that begins with `git-`, Git will use it as a subcommand. For example, `git current-branch` will run the `bin/git-current-branch` script from this repository.

**Comment by dorianmariefr** [comment]
thanks
