### ISSUE TITLE
zsh profile not fully loading on terminal startup (iTerm2 + Monterrey)

### ISSUE THREAD

**Issue by markelld** [thoughtbot/dotfiles#702]
Hello,

This might be a simple oversight on my part, but I noticed I've had to manually run `source ~/.zshrc` each time I start my terminal, in order to access commands like `node` and `yarn`.

Dotfiles were installed on a new Macbook Air 2022, running Monterrey 12.4 (fresh install).

<img width="395" alt="Screen Shot 2022-07-27 at 3 47 47 PM" src="https://user-images.githubusercontent.com/60442714/181369458-74b2c02a-5585-4181-b829-7f6ecc74b3a6.png">

Here is my `$PATH` before and after running `source`:
<img width="1463" alt="Screen Shot 2022-07-27 at 3 40 22 PM" src="https://user-images.githubusercontent.com/60442714/181369452-425eefd8-f10f-4842-bbb5-1aec0f9ec9a7.png">

I ran followed the instructions on the README, but seems like an additional step is required? 
Could it be a preference/setting in iTerm2?

Thanks in advance.

**Comment by danielnolan** [comment]
Hi @markelld thanks for the report. Could you try creating a `.zprofile` in your home directory with the following entry
`eval "$(/opt/homebrew/bin/brew shellenv)"` and see if that resolves your path issue? 
I recently setup an M1 mac and had a similar issue until I added `.zprofile` with this command.

**Comment by markelld** [comment]
@danielnolan  So I tried this command but it has not rectified the issue, sorry for the late reply. Also I am getting not output from the command.

**Comment by danielnolan** [comment]
@markelld did you try @mrjonesbot suggestion? Is this still an issue for you?
